# Generated by Django 2.2.3 on 2019-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Dateofbirth', models.DateField(verbose_name='DOB')),
                ('Dateofdeath', models.DateField(blank=True, null=True, verbose_name='DOD')),
                ('Summery', models.TextField(default='Please enter the summery details of Employee', max_length=500)),
                ('deathindicator', models.BooleanField()),
            ],
        ),
    ]
